/**
 * Regenerate the typed TypeScript SDK client from the live
 * OpenAPI 3.x spec generated by the NAS backend.
 *
 *   $ npm run openapi:generate
 *
 * Boots the Nest app IN-PROCESS (no DB / Redis required — both
 * pings are stubbed to no-ops), captures the spec via
 * ``app.getHttpServer()``, runs ``openapi-typescript`` against it,
 * and writes the result to ``clients/ts/api.d.ts``.
 *
 * PR-N6 (issue #90) intentionally keeps the generated file in
 * version control so SDK consumers (``apps/mac``, ``apps/web``)
 * get exact type checking against the current server behaviour.
 * CI then runs ``npm run openapi:check`` which only fails when
 * the regenerated copy drifts from the committed one.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { Test, TestingModule } from '@nestjs/testing';
import request from 'supertest';
import openapiTS, { astToString } from 'openapi-typescript';
import { AppModule } from '../src/app.module';
import { buildValidationPipe } from '../src/common/validation.pipe';
import { mountOpenApi } from '../src/common/openapi.bootstrap';

const OUT_PATH = resolve(__dirname, '..', 'clients', 'ts', 'api.d.ts');

async function main(): Promise<void> {
  // eslint-disable-next-line no-console
  console.log('[openapi] booting in-process app to snapshot the spec');

  // The same bootstrap shape every e2e spec in this repo uses.
  // Database + Redis pings are stubbed so the script does not
  // need containers to succeed.
  process.env.NAS_PAIR_PIN = process.env.NAS_PAIR_PIN ?? '12345678';
  process.env.NAS_JWT_SECRET =
    process.env.NAS_JWT_SECRET ?? 'test-secret-do-not-use-in-prod-must-be-32+bytes';

  const moduleRef: TestingModule = await Test.createTestingModule({
    imports: [AppModule],
  })
    .overrideProvider('DATABASE_PING')
    .useValue(async () => undefined)
    .overrideProvider('REDIS_PING')
    .useValue(async () => undefined)
    .compile();
  const app = moduleRef.createNestApplication();
  // Order is critical — mountOpenApi MUST run before app.init()
  // because middleware added after init is invisible to the
  // ``request(app.getHttpServer())`` pattern (see
  // ``src/common/openapi.bootstrap.ts``).
  mountOpenApi(app);
  app.useGlobalPipes(buildValidationPipe());
  await app.init();

  try {
    // eslint-disable-next-line no-console
    console.log('[openapi] GET /api/docs-json');
    const res = await request(app.getHttpServer()).get('/api/docs-json').expect(200);
    const spec = res.body as Record<string, unknown>;

    // eslint-disable-next-line no-console
    console.log('[openapi] generating AST');
    const ast = await openapiTS(spec as unknown as Parameters<typeof openapiTS>[0]);

    // eslint-disable-next-line no-console
    console.log(`[openapi] serialising to ${OUT_PATH}`);
    mkdirSync(dirname(OUT_PATH), { recursive: true });
    writeFileSync(
      OUT_PATH,
      astToString(ast as Parameters<typeof astToString>[0]),
      'utf8',
    );
    // eslint-disable-next-line no-console
    console.log(`[openapi] OK — wrote ${OUT_PATH}`);
  } finally {
    await app.close();
  }
}

main().catch((err: unknown) => {
  // eslint-disable-next-line no-console
  console.error('[openapi] FAILED:', err);
  process.exit(1);
});
